version: '3.8'

services:
  #Nginx server
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - abz

  #Laravel project
  laravel:
    build:
      context: ./
      dockerfile: ./.docker/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/
      - ./.docker/php/entrypoint.sh:/var/www/entrypoint.sh
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/laravel.ini
    depends_on:
      - db
    networks:
      - abz


  #MySQL database server
  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: abz_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata/:/var/lib/mysql/
    networks:
      - abz

volumes:
  cache:
    driver: local

networks:
  abz:
    driver: bridge